# Generated by Django 5.1.4 on 2024-12-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
