# Generated by Django 5.1.4 on 2024-12-29 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_review'),
        ('user_manager', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'order', 'product'), name='unique_return_per_product')],
            },
        ),
    ]
